apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: markdown-live
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      run: markdown-live
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: markdown-live
    spec:
      containers:
      - env:
        - name: HOST
          value: markdown.dichev.io
        - name: COOKIE
          valueFrom:
            secretKeyRef:
              key: value
              name: erlang-cookie
        image: gcr.io/dichev-io/markdown_live:0.1.4
        imagePullPolicy: IfNotPresent
        name: markdown-live
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30