apiVersion: v1
kind: Service
metadata:
  labels:
    run: markdown-live
  name: markdown-live
  namespace: default
spec:
  type: LoadBalancer
  selector:
    run: markdown-live
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000